# Generated by Django 5.2.10 on 2026-01-23 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher_name', models.CharField(db_index=True, max_length=255)),
                ('title', models.TextField(blank=True)),
                ('title_hash', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64, verbose_name='بصمة العنوان')),
                ('degree', models.CharField(choices=[('MA', 'ماجستير'), ('PHD', 'دكتوراه')], db_index=True, max_length=10)),
                ('researcher_type', models.CharField(choices=[('RESEARCHER', 'باحث'), ('ASSISTANT', 'معيد')], db_index=True, default='RESEARCHER', max_length=20, verbose_name='النوع')),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('frame_date', models.DateField(blank=True, null=True)),
                ('university_approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'مسجل'), ('DISCUSSED', 'ناقش/انتهى'), ('CANCELLED', 'إلغاء'), ('DISMISSED', 'فصل'), ('OTHER', 'أخرى')], db_index=True, default='REGISTERED', max_length=20)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('status_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researches', to='core.department', verbose_name='قسم الباحث')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='core.department', verbose_name='قسم المشرف')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'رئيسي'), ('CO', 'مشارك'), ('EXTERNAL', 'خارجي')], default='PRIMARY', max_length=20)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.research')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supervisor')),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='supervisors',
            field=models.ManyToManyField(related_name='researches', through='core.ResearchSupervision', to='core.supervisor'),
        ),
        migrations.AddConstraint(
            model_name='researchsupervision',
            constraint=models.UniqueConstraint(fields=('research', 'supervisor'), name='uniq_research_supervisor'),
        ),
        migrations.AddIndex(
            model_name='research',
            index=models.Index(fields=['researcher_name', 'degree'], name='core_resear_researc_8e6bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='research',
            index=models.Index(fields=['title_hash'], name='core_resear_title_h_35b7fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='research',
            constraint=models.UniqueConstraint(fields=('researcher_name', 'title_hash', 'degree', 'researcher_type'), name='uniq_research_by_name_titlehash_degree_type'),
        ),
    ]
