# Generated by Django 5.2.10 on 2026-02-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='research',
            name='frame_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإطار'),
        ),
        migrations.AlterField(
            model_name='research',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='research',
            name='status_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الحالة'),
        ),
        migrations.AlterField(
            model_name='research',
            name='status_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة الحالة'),
        ),
        migrations.AlterField(
            model_name='research',
            name='university_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ موافقة الجامعة'),
        ),
        migrations.CreateModel(
            name='ResearchFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='core.research', verbose_name='الباحث')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('research', 'year')},
            },
        ),
    ]
