# Generated by Django 5.2.10 on 2026-02-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_research_phone_supervisor_email_supervisor_phone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='researchfeepayment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='phone',
        ),
        migrations.AlterField(
            model_name='research',
            name='researcher_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='اسم الباحث'),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'مسجل'), ('DISCUSSED', 'ناقش/انتهى'), ('CANCELLED', 'إلغاء'), ('DISMISSED', 'فصل'), ('OTHER', 'أخرى')], db_index=True, default='REGISTERED', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.TextField(blank=True, verbose_name='عنوان الرسالة'),
        ),
        migrations.AddConstraint(
            model_name='researchfeepayment',
            constraint=models.UniqueConstraint(fields=('research', 'year'), name='uniq_fee_payment_per_year'),
        ),
    ]
