# Generated by Django 5.2.10 on 2026-02-01 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_researchfeepayment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='researchfeepayment',
            name='uniq_fee_payment_per_year',
        ),
        migrations.AddField(
            model_name='researchfeepayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='researchfeepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='researcher_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'مسجل'), ('DISCUSSED', 'ناقش/انتهى'), ('CANCELLED', 'إلغاء'), ('DISMISSED', 'فصل'), ('OTHER', 'أخرى')], db_index=True, default='REGISTERED', max_length=20),
        ),
        migrations.AlterField(
            model_name='research',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='status_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='researchfeepayment',
            constraint=models.UniqueConstraint(fields=('research', 'year'), name='uniq_research_fee_year'),
        ),
    ]
